Added an 'Edit Artifact' functionality
Ohkthx/mfah-webapp-java pull request #11
Opened 2023-11-10 20:50 UTC by Itaho

Reports come next

2023-11-10 21:33 UTC, Itaho commented
There is a weird check that fails with Maven. I'm not sure what its meant for but its flagging the HTML edit to employee.html and i have no clue as to what it means. If its a problem then I'll figure it out but I didn't have any issues running it

2023-11-13 01:41 UTC, Ohkthx requested changes
Handlers were not updated in App.java.

2023-11-13 01:41 UTC, Ohkthx commented on src/main/java/com/mfahproj/webapp/App.java
> +        server.createContext("/collection/register", new MiddlewareHandler(new ArtifactHandler(), callback));
The handler called for registering a collection is `ArtifactHandler()` here.

2023-11-13 01:41 UTC, Ohkthx commented on src/main/java/com/mfahproj/webapp/App.java
> +        server.createContext("/program/register", new MiddlewareHandler(new ArtifactHandler(), callback));
The handler called for registering a program is `ArtifactHandler()` here.

2023-11-13 01:41 UTC, Ohkthx commented on src/main/java/com/mfahproj/webapp/App.java
> +        server.createContext("/collection/edit", new MiddlewareHandler(new EditArtifactHandler(), callback));
The handler called for editing a collection is `EditArtifactHandler()` here.

2023-11-13 01:41 UTC, Ohkthx commented on src/main/java/com/mfahproj/webapp/App.java
> +        server.createContext("/program/edit", new MiddlewareHandler(new EditArtifactHandler(), callback));
The handler called for editing a program is `EditArtifactHandler()` here.

2023-11-13 04:01 UTC, Itaho reviewed
Fixed App.java and renamed ProgramHandler to RegisterProgramHandler

2023-11-14 01:21 UTC, closed without merging